apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: maven
    image: maven:3.6.3-openjdk-8
    command:
    - cat
    tty: true
  - name: python
    image: python:3.8-slim
    command:
    - cat
    tty: true
